repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--safe]
  # pyhton -m unittest
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -m unittest
        language: system
        pass_filenames: false
        args: ["discover"]